name: vscode dev container CI
on:
  push:
    branches: [ "main" ]
    paths:
      - 'vscode-dev-container/**'
  schedule:
    - cron: '19 19 19 * *'
  workflow_dispatch:

jobs:
  build-push:
    uses: oliviertremblaynoel/gha-pipelines/.github/workflows/ci.yml@main
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    with:
      PROJECT_NAME: ${{ github.event.repository.name }}
      FOLDER: vscode-dev-container
